export const countries = [
    { code: 'br', name: 'Brasil', ddi: '+55' },
    { code: 'us', name: 'Estados Unidos', ddi: '+1' },
    { code: 'pt', name: 'Portugal', ddi: '+351' },
    { code: 'ao', name: 'Angola', ddi: '+244' },
    { code: 'mz', name: 'Moçambique', ddi: '+258' },
    { code: 'py', name: 'Paraguai', ddi: '+595' },
    { code: 'uy', name: 'Uruguai', ddi: '+598' },
    { code: 'ar', name: 'Argentina', ddi: '+54' },
    { code: 'cl', name: 'Chile', ddi: '+56' },
    { code: 'co', name: 'Colômbia', ddi: '+57' },
    { code: 'pe', name: 'Peru', ddi: '+51' },
    { code: 'mx', name: 'México', ddi: '+52' },
    { code: 'es', name: 'Espanha', ddi: '+34' },
    { code: 'fr', name: 'França', ddi: '+33' },
    { code: 'de', name: 'Alemanha', ddi: '+49' },
    { code: 'it', name: 'Itália', ddi: '+39' },
    { code: 'gb', name: 'Reino Unido', ddi: '+44' },
    { code: 'ca', name: 'Canadá', ddi: '+1' },
    { code: 'au', name: 'Austrália', ddi: '+61' },
    { code: 'jp', name: 'Japão', ddi: '+81' },
    { code: 'cn', name: 'China', ddi: '+86' },
    { code: 'in', name: 'Índia', ddi: '+91' },
    { code: 'ru', name: 'Rússia', ddi: '+7' },
    { code: 'za', name: 'África do Sul', ddi: '+27' },
    { code: 'ch', name: 'Suíça', ddi: '+41' },
    { code: 'se', name: 'Suécia', ddi: '+46' },
    { code: 'no', name: 'Noruega', ddi: '+47' },
    { code: 'dk', name: 'Dinamarca', ddi: '+45' },
    { code: 'fi', name: 'Finlândia', ddi: '+358' },
    { code: 'be', name: 'Bélgica', ddi: '+32' },
    { code: 'nl', name: 'Holanda', ddi: '+31' },
    { code: 'ie', name: 'Irlanda', ddi: '+353' },
    { code: 'nz', name: 'Nova Zelândia', ddi: '+64' },
    { code: 'sg', name: 'Cingapura', ddi: '+65' },
    { code: 'kr', name: 'Coreia do Sul', ddi: '+82' },
    { code: 'ae', name: 'Emirados Árabes', ddi: '+971' },
    { code: 'sa', name: 'Arábia Saudita', ddi: '+966' },
    { code: 'il', name: 'Israel', ddi: '+972' },
    { code: 'tr', name: 'Turquia', ddi: '+90' },
    { code: 'eg', name: 'Egito', ddi: '+20' },
    { code: 'gr', name: 'Grécia', ddi: '+30' },
    { code: 'pl', name: 'Polônia', ddi: '+48' },
    { code: 'cz', name: 'República Tcheca', ddi: '+420' },
    { code: 'hu', name: 'Hungria', ddi: '+36' },
    { code: 'at', name: 'Áustria', ddi: '+43' },
    { code: 'bo', name: 'Bolívia', ddi: '+591' },
    { code: 'ec', name: 'Equador', ddi: '+593' },
    { code: 've', name: 'Venezuela', ddi: '+58' },
    { code: 'pa', name: 'Panamá', ddi: '+507' },
    { code: 'cr', name: 'Costa Rica', ddi: '+506' },
    { code: 'do', name: 'República Dominicana', ddi: '+1' },
    { code: 'cu', name: 'Cuba', ddi: '+53' },
    { code: 'cv', name: 'Cabo Verde', ddi: '+238' },
    { code: 'gw', name: 'Guiné-Bissau', ddi: '+245' },
    { code: 'st', name: 'São Tomé e Príncipe', ddi: '+239' },
    { code: 'tl', name: 'Timor-Leste', ddi: '+670' },
]
